### ISSUE TITLE
How about add an API RedLock::try_lock() ?

### ISSUE THREAD

**Issue by TheWaWaR** [badboy/redlock-rs#5]
Some thing like this:
``` rust
pub fn try_lock<'a>(
    &'a self, 
    resource: &'a [u8],
    ttl: usize,
    retry_count: u32,
    retry_delay: u32
) -> Option<Lock> {  /*...*/ }
```

Because sometimes we want different (retry_count, retry_delay) pairs for the same client.

**Comment by badboy** [comment]
I‘m not actively developing redlock-rs. Feel free to take the code and extend it. 
If you want to take over I can add you as a maintainer.
